import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-my-note',
  templateUrl: './my-note.component.html',
  styleUrls: ['./my-note.component.scss'],
})
export class MyNoteComponent implements OnInit {
  // Datos de prueba local - posible llegada de informacion JSON
  procesos = [
    {
      nombre: 'Creditos aprobados',
      aprovados: 90,
    },
    {
      nombre: 'Materias aprobadas',
      aprovados: 80,
    },
    {
      nombre: 'Materias del pensum',
      aprovadodas: 70,
      noTomadas: 5,
      periodoActual: 5,
    },
  ];
  niveles = [
    {
      nombre: 'Nivel 1',
      materias: [
        {
          codigo: 'CD123',
          nombre: 'Calculo diferencial',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'AL123',
          nombre: 'Algebra lineal',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'FI123',
          nombre: 'Fisica I',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'FP123',
          nombre: 'Fundamentos de programacion',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'II123',
          nombre: 'Introduccion a la informatica',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'MI123',
          nombre: 'Metodo de la investigacion',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '3',
        },
        {
          codigo: 'CF123',
          nombre: 'Cultura fisica',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '2',
        },
      ],
    },
    {
      nombre: 'Nivel 2',
      materias: [
        {
          codigo: 'CI123',
          nombre: 'Calculo integral',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'MD123',
          nombre: 'Matematicas discretas',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'FII123',
          nombre: 'Fisica II',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'POO123',
          nombre: 'Programacion orientada a objeto',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'SO123',
          nombre: 'Sistema operativo',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'TS123',
          nombre: 'Teoria de sistemas',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '3',
        },
        {
          codigo: 'CF123',
          nombre: 'Tecnicas de expresion oral y escrita',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '2',
        },
      ],
    },
    {
      nombre: 'Nivel 3',
      materias: [
        {
          codigo: 'CD123',
          nombre: 'Calculo vectorial',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'AL123',
          nombre: 'Estructura de datos',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'FI123',
          nombre: 'Electronica',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'FP123',
          nombre: 'Programacion aplicada a web',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'II123',
          nombre: 'Aplicacion de sistemas operativos',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'MI123',
          nombre: 'Analisis de sistemas',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
      ],
    },
    {
      nombre: 'Nivel 4',
      materias: [
        {
          codigo: 'CD123',
          nombre: 'Ecuaciones diferenciales',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'AL123',
          nombre: 'Analisis y diseno de base de datos',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'FI123',
          nombre: 'Sistema digital',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'FP123',
          nombre: 'Programacion movil',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'II123',
          nombre: 'Mantenimiento de hardware',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'MI123',
          nombre: 'Ingenieria de software I',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'CF123',
          nombre: 'Proyecto integrador I',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '3',
        },
      ],
    },
    {
      nombre: 'Nivel 5',
      materias: [
        {
          codigo: 'CD123',
          nombre: 'Probabilidad y estadistica',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'FP123',
          nombre: 'Administracion de base de datos',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'II123',
          nombre: 'Organizacion y arquitectura de computadoras',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'MI123',
          nombre: 'Sistemas expertos I',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'CF123',
          nombre: 'Sistema de comunicacion',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'CF123',
          nombre: 'Ingenieria de software II',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
      ],
    },
    {
      nombre: 'Nivel 6',
      materias: [
        {
          codigo: 'CD123',
          nombre: 'Metodo numericos',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'AL123',
          nombre: 'Base de datos distribuidas',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'FI123',
          nombre: 'Contabilidad I',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'FP123',
          nombre: 'Sistemas expertos II',
          partUno: 0.0,
          partDos: 0.0,
          recup: 0.0,
          final: 0.0,
          estado: 'Periodo actual',
          creditos: '4',
        },
        {
          codigo: 'II123',
          nombre: 'Redes de computacion I',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'MI123',
          nombre: 'Gestion de calidad de software',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
      ],
    },
    {
      nombre: 'Nivel 7',
      materias: [
        {
          codigo: 'IO123',
          nombre: 'Investigacion de operaciones',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'AHC123',
          nombre: 'Aplicacion de herramientas case',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'CII123',
          nombre: 'Contabilidad II',
          partUno: 0.0,
          partDos: 0.0,
          recup: 0.0,
          final: 0.0,
          estado: 'No tomado',
          creditos: '4',
        },
        {
          codigo: 'OI123',
          nombre: 'Optativa I',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '10',
        },
        {
          codigo: 'RCII123',
          nombre: 'Redes de computadores II',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'SD123',
          nombre: 'Sistemas distribuidos',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '3',
        },
        {
          codigo: 'CF123',
          nombre: 'Proyecto integrador II',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '3',
        },
      ],
    },
    {
      nombre: 'Nivel 8',
      materias: [
        {
          codigo: 'TS123',
          nombre: 'Tecnica de simulacion',
          partUno: 0.0,
          partDos: 0.0,
          recup: 0.0,
          final: 0.0,
          estado: 'No tomado',
          creditos: '4',
        },
        {
          codigo: 'SCG123',
          nombre: 'Sistemas corporativo de gestion',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'AE123',
          nombre: 'Administracion de empresa',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '3',
        },
        {
          codigo: 'GP123',
          nombre: 'Gestion de proyecto',
          partUno: 0.0,
          partDos: 0.0,
          recup: 0.0,
          final: 0.0,
          estado: 'Periodo actual',
          creditos: '4',
        },
        {
          codigo: 'AS123',
          nombre: 'Administracion de servidores',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'TSI123',
          nombre: 'Tecnologia de seguridad de la informacion',
          partUno: 10.0,
          partDos: 9.0,
          recup: 0.0,
          final: 19.0,
          estado: 'Aprobado',
          creditos: '3',
        },
      ],
    },
    {
      nombre: 'Nivel 9',
      materias: [
        {
          codigo: 'IG123',
          nombre: 'Inteligencia de negocios',
          partUno: 0.0,
          partDos: 0.0,
          recup: 0.0,
          final: 0.0,
          estado: 'Periodo actual',
          creditos: '4',
        },
        {
          codigo: 'RHCO123',
          nombre: 'Relaciones humanas y comportamiento organizacional',
          partUno: 0.0,
          partDos: 0.0,
          recup: 0.0,
          final: 0.0,
          estado: 'Periodo actual',
          creditos: '3',
        },
        {
          codigo: 'ENT123',
          nombre: "Emprendimiento de negocios en TIC'S",
          partUno: 0.0,
          partDos: 0.0,
          recup: 0.0,
          final: 0.0,
          estado: 'No tomada',
          creditos: '4',
        },
        {
          codigo: 'AUI123',
          nombre: 'Administracion de unidades informaticas',
          partUno: 0.0,
          partDos: 0.0,
          recup: 0.0,
          final: 0.0,
          estado: 'Periodo actual',
          creditos: '3',
        },
        {
          codigo: 'EAS123',
          nombre: 'Evaluacion y auditoria de sistema',
          partUno: 0.0,
          partDos: 0.0,
          recup: 0.0,
          final: 0.0,
          estado: 'Periodo actual',
          creditos: '4',
        },
        {
          codigo: 'GT123',
          nombre: 'Guia de titulacion',
          partUno: 0.0,
          partDos: 0.0,
          recup: 0.0,
          final: 0.0,
          estado: 'Periodo actual',
          creditos: '2',
        },
      ],
    },
    {
      nombre: 'Nivel 10',
      materias: [
        {
          codigo: 'CI123',
          nombre: 'Derecho informatico',
          partUno: 0.0,
          partDos: 0.0,
          recup: 0.0,
          final: 0.0,
          estado: 'No tomado',
          creditos: '2',
        },
        {
          codigo: 'AEI123',
          nombre: 'Analisis economico de inversiones',
          partUno: 0.0,
          partDos: 0.0,
          recup: 0.0,
          final: 0.0,
          estado: 'No tomado',
          creditos: '3',
        },
        {
          codigo: 'OII123',
          nombre: 'Optativa II',
          partUno: 9.14,
          partDos: 8.4,
          recup: 0.0,
          final: 17.54,
          estado: 'Aprobado',
          creditos: '4',
        },
      ],
    },
    {
      nombre: 'Seminarios',
      materias: [
        {
          codigo: 'VEP123',
          nombre: 'Valores y etica profesional',
          partUno: 10.0,
          partDos: 10.0,
          recup: 0.0,
          final: 10.0,
          estado: 'Aprobado',
          creditos: '2',
        },
        {
          codigo: 'SMEI123',
          nombre: 'Socioeconomica de Manabi y el Ecuador',
          partUno: 0.0,
          partDos: 0.0,
          recup: 0.0,
          final: 0.0,
          estado: 'No tomado',
          creditos: '2',
        },
        {
          codigo: 'MAPC123',
          nombre: 'Medio ambiente, proteccion y conservacion',
          partUno: 0.0,
          partDos: 0.0,
          recup: 0.0,
          final: 0.0,
          estado: 'Periodo actual',
          creditos: '2',
        },
        {
          codigo: 'IIC123',
          nombre: 'Ingles I',
          partUno: 10.0,
          partDos: 10.0,
          recup: 0.0,
          final: 10.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'III123',
          nombre: 'Ingles II',
          partUno: 0.0,
          partDos: 0.0,
          recup: 0.0,
          final: 0.0,
          estado: 'Aprobado',
          creditos: '4',
        },
        {
          codigo: 'III123',
          nombre: 'Ingles III',
          partUno: 7.0,
          partDos: 7.6,
          recup: 0.0,
          final: 14.6,
          estado: 'Aprobado',
          creditos: '4',
        },
      ],
    },
    {
      nombre: 'Titulacion',
      materias: [
        {
          codigo: 'PPI123',
          nombre: 'Practica preprofesionales I',
          partUno: 0.0,
          partDos: 0.0,
          recup: 0.0,
          final: 18.76,
          estado: 'Aprobado',
          creditos: '5',
        },
        {
          codigo: 'PPII123',
          nombre: 'Practica preprofesionales II',
          partUno: 0.0,
          partDos: 0.0,
          recup: 0.0,
          final: 18.7,
          estado: 'Aprobado',
          creditos: '5',
        },
        {
          codigo: 'VS123',
          nombre: 'Viculacion con la sociedad',
          partUno: 0.0,
          partDos: 0.0,
          recup: 0.0,
          final: 20.0,
          estado: 'Aprobado',
          creditos: '2',
        },
        {
          codigo: 'TI123',
          nombre: 'Trabajo de titulacion',
          partUno: 0.0,
          partDos: 0.0,
          recup: 0.0,
          final: 0.0,
          estado: 'No tomado',
          creditos: '4',
        },
      ],
    },
  ];
  materiasReprobadas = [
    {
      codigo: 'SEI35994',
      nombre: 'Sistemas expertos I',
      partUno: 8.35,
      partDos: 1.98,
      final: 8.0,
      recup: 0.0,
      suma: 13.63,
      estado: 'Reprobado por notas',
    },
    {
      codigo: 'MN15384',
      nombre: 'Metodos numericos',
      partUno: 5.31,
      partDos: 8.08,
      final: 4.5,
      recup: 0.0,
      suma: 11.2,
      estado: 'Reprobado por notas',
    },
    {
      codigo: 'GDCDS31263',
      nombre: 'Gestion de calidad del software',
      partUno: 6.4,
      partDos: 7.2,
      final: 4.0,
      recup: 0.0,
      suma: 10.8,
      estado: 'Reprobado por notas',
    },
    {
      codigo: 'SEI24267',
      nombre: 'Sistemas expertos II',
      partUno: 7.28,
      partDos: 4.48,
      final: 3.75,
      recup: 0.0,
      suma: 9.63,
      estado: 'Reprobado por notas',
    },
  ];
  materiasPensum = [
    {
      codigo: 'VYEP35469',
      nombre: 'SEM. VALOR Y ETICA PROFESIONAL',
      partUno: 10.0,
      partDos: 10.0,
      final: 0.0,
      recup: 0.0,
      suma: 20.0,
      estado: 'Aprobado',
      creditos: '2',
    },
  ];

  // Variable para almacenar los resultados por nivel
  resultadoNivel: any;
  // Variable para inicialinar nivel actual
  selectedIndex = 8;
  // Variables de creditos
  creditosAprobados = 90;
  noProbados = 100 - this.creditosAprobados;

  // Variables para demostrar en los chart.js
  labelCreditosAprobados = ['Aprobados', 'No Aprobados'];
  colorCreditosAprobados = ['#7BED8D', '#f7f7f7'];
  dataCreditosAprobados = [this.creditosAprobados, this.noProbados];

  labelMateriasAprobados = ['Aprobados', 'No Aprobados'];
  colorMateriasAprobados = ['#7BED8D', '#f7f7f7'];
  dataMateriasAprobados = [80, 20];

  labelMateriasPensum = ['Aprobados', 'Perido actual', 'No tomadas'];
  colorMateriasPensum = ['#7BED8D', '#11CDEF', '#F53C56'];
  dataMateriasPensum = [80, 20, 10];

  constructor() {}

  ngOnInit(): void {
    // se inicializa el nivel actual
    this.mostrarNivel('Nivel 9');
  }
  // Metodo que nos permite mostrar en las TABS por nivel
  mostrarNivel(nivel: string) {
    this.resultadoNivel = this.niveles.find((n: any) => n.nombre === nivel);
  }
}
